SET SCHEMA TEAM01;
DROP TABLE ABTEILUNG;
DROP TABLE ANGESTELLTE;
CREATE TABLE ABTEILUNG
	( DEPT_ID varchar(2) NOT NULL
	, NAME varchar(22) NOT NULL
	, BUDGET integer
	, PERSONALKOSTEN integer
	, UMLAGEN integer )
;

CREATE TABLE ANGESTELLTE
	( PERSNR varchar(4) NOT NULL
	, SOZVERSNR varchar(16) NOT NULL
	, NAME varchar(10) NOT NULL
	, ABTEILUNG char(2)
	, GEHALT integer NOT NULL
	, ZULAGE integer )
;

ALTER TABLE ABTEILUNG
	ADD CONSTRAINT PK PRIMARY KEY 
	( DEPT_ID );

ALTER TABLE ANGESTELLTE
	ADD CONSTRAINT PK PRIMARY KEY 
	( PERSNR
	, ABTEILUNG );

ALTER TABLE ANGESTELLTE
	ADD CONSTRAINT ANGESTELLTE_ABTEILUNG FOREIGN KEY
	( ABTEILUNG )
	REFERENCES ABTEILUNG
	( DEPT_ID )
	ON DELETE CASCADE; 

GRANT ALL ON ANGESTELLTE TO PUBLIC;
GRANT ALL ON ABTEILUNG TO PUBLIC;