INSERT INTO LECTURE (LECTURE_NUMBER, LECTURE_NAME, LECTURE_COMMENTS, SEMESTER, CREDIT_AMOUNT, PWZ, SEMESTER_HOURS_SPO)
SELECT SBJNO, SBJNAME, LECNOTES, SBJLEVEL, NUMCURR, ELECTIVE, NUMSCHD
	FROM(
		SELECT
		SBJNO, 
		SBJNAME, 
		LECNOTES,
		SBJLEVEL, 
		NUMCURR, 
		ELECTIVE, 
		NUMSCHD,
		ROW_NUMBER() OVER(PARTITION BY SBJNO ORDER BY LECNOTES) rn
		FROM RAWDATA 
	) a
WHERE rn = 1		
ORDER BY SBJNAME DESC
;