INSERT INTO EVENT (LECTURE_NUMBER, COURSE, CURRENT_SEMESTER, SEMESTER_HOURS_ACTUAL, EVENT_COMMENTS, SEMESTER_HOURS_SPO_ACTUAL, DEPARTMENT, DEPARTMENT_IMPORTED_FROM)
SELECT SBJNO, STUDYPRG, TERM, CNTSCHD, LECNOTES, CNTCURR, DEPT, DEPTEX
	FROM(
		SELECT
		SBJNO, 
		STUDYPRG,
		TERM, 
		CNTSCHD, 
		LECNOTES, 
		CNTCURR,
		CASE
			when RAWDATA.DEPT = 'IT' then RAWDATA.DEPT
			else 'IT'
		END as DEPT,
		CASE
			when RAWDATA.DEPT != 'IT' then RAWDATA.DEPT
		END as DEPTEX,
		ROW_NUMBER() OVER(PARTITION BY SBJNO ORDER BY LECNOTES) rn
		FROM RAWDATA 
	) a
WHERE rn = 1		
ORDER BY SBJNO
;


