--@author eumuit00
--THIS SCRIPT IS FOR TESTING THE TRIGGER ON THE VIES
echo "----------------------------";
echo "EXECUTE: _testScript.sql";
echo "----------------------------";
echo "";
--TEST CODE FOR COURSE PLANNER------------------------------------------------
echo "----------------------------";
echo "TEST CODE FOR COURSE PLANNER";
echo "----------------------------";
echo "INSERT INTO COURSE_PLANNER - ('SS16', '000001' ,'testfach','SWB', '2', 'P', 2, '2', 2, 2)";
INSERT INTO COURSE_PLANNER (current_semester, lecture_number, lecture_name, course, semester, pwz, credit_amount, event_comments, semester_hours_spo, semester_hours_actual )
VALUES ('SS16', '000001' ,'testfach','SWB', '2', 'P', 2, '2', 2, 2);

echo "Get the created lecture";
SELECT LECTURE_NUMBER, LECTURE_NAME
FROM LECTURE
WHERE LECTURE_NUMBER = '000001';

echo "UPDATE COURSE_PLANNER - '000001' new = ('new_testfach', '7', 'SWM', '000002')";
UPDATE COURSE_PLANNER
SET lecture_name = 'new_testfach', semester = '7', course = 'SWM', lecture_number = '000002'
WHERE lecture_number = '000001';

echo "Get the changed lecture";
SELECT LECTURE_NUMBER, LECTURE_NAME
FROM LECTURE
WHERE LECTURE_NUMBER = '000002';

echo "DELETE FROM COURSE_PLANNER - '000002' ";
DELETE FROM COURSE_PLANNER
WHERE LECTURE_NUMBER = '000002';

echo "Get the deleted lecture";
SELECT LECTURE_NUMBER, LECTURE_NAME
FROM LECTURE
WHERE LECTURE_NUMBER = '000002';

echo "----------------------------";


--TEST CODE FOR MATCHMAKER----------------------------------------------------
echo "TEST CODE FOR MATCHMAKER";
echo "----------------------------";

echo "Get Initial Workloads";
SELECT LECTURER.NAME, PROFESSOR.WORKLOAD_ACTUAL
FROM LECTURER INNER JOIN PROFESSOR
ON LECTURER.LECTURER_NUMBER = PROFESSOR.LECTURER_NUMBER
WHERE LECTURER.NAME = 'Keller' OR LECTURER.NAME = 'Beck';

echo "INSERT INTO MATCHMAKER - ('SWT', '6', 'SS15', 'Datenbanken 2', 2, 2, 2, 'Keller','test code')";
INSERT INTO MATCHMAKER (
	COURSE, SEMESTER, CURRENT_SEMESTER, LECTURE_NAME,
	SEMESTER_HOURS_SPO_ACTUAL, SEMESTER_HOURS_ACTUAL,
	SPLIT_WORKLOAD, NAME, EVENT_COMMENTS)
VALUES(
	'SWT', '6', 'SS15', 'Datenbanken 2',
	2, 2, 2, 'Keller','test code')
;

echo "Check Workloads after Insert";
SELECT LECTURER.NAME, PROFESSOR.WORKLOAD_ACTUAL
FROM LECTURER INNER JOIN PROFESSOR
ON LECTURER.LECTURER_NUMBER = PROFESSOR.LECTURER_NUMBER
WHERE LECTURER.NAME = 'Keller' OR LECTURER.NAME = 'Beck';

echo "UPDATE MATCHMAKER - 'SWT' '6' 'SS15' 'Datenbanken 2' 'Keller' new = ( SPLIT_WORKLOAD = 4, NAME = 'Beck')";
UPDATE MATCHMAKER
SET  	SPLIT_WORKLOAD = 2, NAME = 'Beck'
WHERE 	COURSE = 'SWT' AND SEMESTER = '6' AND CURRENT_SEMESTER = 'SS15' 
AND 	LECTURE_NAME = 'Datenbanken 2' AND NAME = 'Keller'
;

echo "Check Workloads after Update";
SELECT LECTURER.NAME, PROFESSOR.WORKLOAD_ACTUAL
FROM LECTURER INNER JOIN PROFESSOR
ON LECTURER.LECTURER_NUMBER = PROFESSOR.LECTURER_NUMBER
WHERE LECTURER.NAME = 'Keller' OR LECTURER.NAME = 'Beck';

echo "DELETE FROM COURSE_PLANNER - 'SWT' '6' 'SS15' 'Datenbanken 2' 'Beck' ";
DELETE FROM MATCHMAKER
WHERE 	COURSE = 'SWT' AND SEMESTER = '6' AND CURRENT_SEMESTER = 'SS15' 
AND 	LECTURE_NAME = 'Datenbanken 2' AND NAME = 'Beck'
;

echo "Check Workloads after Delete";
SELECT LECTURER.NAME, PROFESSOR.WORKLOAD_ACTUAL
FROM LECTURER INNER JOIN PROFESSOR
ON LECTURER.LECTURER_NUMBER = PROFESSOR.LECTURER_NUMBER
WHERE LECTURER.NAME = 'Keller' OR LECTURER.NAME = 'Beck';
echo "----------------------------";

--TEST CODE FOR WORKLOAD REDUCTION----------------------------------------------------
echo "TEST CODE FOR ORKLOAD REDUCTION";
echo "----------------------------";
echo "INSERT INTO WORKLOAD_REDUCTION - ('SS15' , 'Beck', 'Ausland', 8)";
INSERT INTO WORKLOAD_REDUCTION( TERM, NAME, WORKLOAD_RED_REASON, WORKLOAD_RED_AMOUNT)
VALUES( 'SS15' , 'Beck', 'Ausland', 8)
;

echo "Get the created workload";
SELECT LECTURER.NAME, REDUCTION.WORKLOAD_RED_REASON, REDUCTION.WORKLOAD_RED_AMOUNT  
FROM LECTURER INNER JOIN REDUCTION
ON LECTURER.LECTURER_NUMBER = REDUCTION.LECTURER_NUMBER
WHERE LECTURER.NAME = 'Beck'
;

echo "INSERT INTO WORKLOAD_REDUCTION - ('SS15' , 'Beck', 'Ausland', 8)";
UPDATE WORKLOAD_REDUCTION
SET WORKLOAD_RED_REASON = 'China', WORKLOAD_RED_AMOUNT = 4
WHERE NAME = 'Beck' AND WORKLOAD_RED_REASON = 'Ausland'
;

echo "Get the changed workload";
SELECT LECTURER.NAME, REDUCTION.WORKLOAD_RED_REASON, REDUCTION.WORKLOAD_RED_AMOUNT  
FROM LECTURER INNER JOIN REDUCTION
ON LECTURER.LECTURER_NUMBER = REDUCTION.LECTURER_NUMBER
WHERE LECTURER.NAME = 'Beck'
;

echo "DELETE FROM COURSE_PLANNER - 'SWT' '6' 'SS15' 'Datenbanken 2' 'Beck' ";
DELETE FROM WORKLOAD_REDUCTION
WHERE 	NAME = 'Beck' AND WORKLOAD_RED_REASON = 'China'
;

echo "Get the deleted workload";
SELECT LECTURER.NAME, REDUCTION.WORKLOAD_RED_REASON, REDUCTION.WORKLOAD_RED_AMOUNT  
FROM LECTURER INNER JOIN REDUCTION
ON LECTURER.LECTURER_NUMBER = REDUCTION.LECTURER_NUMBER
WHERE LECTURER.NAME = 'Beck'
;