ALTER TABLE DEPARTMENT
	ADD CONSTRAINT PK PRIMARY KEY 
	( DEPARTMENT_SHORT );

ALTER TABLE EVENT
	ADD CONSTRAINT PK PRIMARY KEY 
	( COURSE
	, LECTURE_NR );

ALTER TABLE EXTERNAL_LECTURER
	ADD CONSTRAINT PK PRIMARY KEY 
	( LECTURER_NUMBER );

ALTER TABLE LECTURE
	ADD CONSTRAINT PK PRIMARY KEY 
	( LECTURE_NR );

ALTER TABLE LECTURER
	ADD CONSTRAINT PK PRIMARY KEY 
	( LECTURER_NUMBER );

ALTER TABLE LECTURER_EVENT
	ADD CONSTRAINT PK PRIMARY KEY 
	( COURSE
	, LECTURE_NR
	, LECTURER_NUMBER );

ALTER TABLE PROFESSOR
	ADD CONSTRAINT PK PRIMARY KEY 
	( WORKLOAD_RED_REASON
	, LECTURER_NUMBER );

ALTER TABLE EVENT
	ADD CONSTRAINT EVENT_LECTURE FOREIGN KEY
	( LECTURE_NR )
	REFERENCES LECTURE
	( LECTURE_NR )
	ON DELETE CASCADE; 

ALTER TABLE EVENT
	ADD CONSTRAINT EVENT_DEPARTMENT FOREIGN KEY
	( IMPORTED_FROM_DEPARTMENT )
	REFERENCES DEPARTMENT
	( DEPARTMENT_SHORT ); 

ALTER TABLE EVENT
	ADD CONSTRAINT EVENT_DEPARTMENT_37 FOREIGN KEY
	( DEPARTMENT )
	REFERENCES DEPARTMENT
	( DEPARTMENT_SHORT ); 

ALTER TABLE EVENT
	ADD CONSTRAINT EVENT_DEPARTMENT_40 FOREIGN KEY
	( DEPARTMENT_124 )
	REFERENCES DEPARTMENT
	( DEPARTMENT_SHORT ); 

ALTER TABLE EVENT
	ADD CONSTRAINT EVENT_DEPARTMENT_39 FOREIGN KEY
	( DEPARTMENT_IMPORTED_FROM )
	REFERENCES DEPARTMENT
	( DEPARTMENT_SHORT ); 

ALTER TABLE EXTERNAL_LECTURER
	ADD CONSTRAINT EXTERNAL_LECTURER_LECTURER FOREIGN KEY
	( LECTURER_NUMBER )
	REFERENCES LECTURER
	( LECTURER_NUMBER )
	ON DELETE CASCADE; 

ALTER TABLE LECTURER_EVENT
	ADD CONSTRAINT LECTURER_EVENT_LECTURER FOREIGN KEY
	( LECTURER_NUMBER )
	REFERENCES LECTURER
	( LECTURER_NUMBER )
	ON DELETE CASCADE; 

ALTER TABLE LECTURER_EVENT
	ADD CONSTRAINT LECTURER_EVENT_EVENT FOREIGN KEY
	( COURSE
	, LECTURE_NR )
	REFERENCES EVENT
	( COURSE
	, LECTURE_NR )
	ON DELETE CASCADE; 

ALTER TABLE PROFESSOR
	ADD CONSTRAINT PROFESSOR_LECTURER FOREIGN KEY
	( LECTURER_NUMBER )
	REFERENCES LECTURER
	( LECTURER_NUMBER )
	ON DELETE CASCADE; 

ALTER TABLE PROFESSOR
	ADD CONSTRAINT PROFESSOR_DEPARTMENT FOREIGN KEY
	( DEPARTMENT_SHORT )
	REFERENCES DEPARTMENT
	( DEPARTMENT_SHORT );