-- @author alriit00, damait06, eumuit00
echo "----------------------------";
echo "EXECUTE: createViews.sql";
echo "----------------------------";
echo "";
ECHO "CREATE VIEW COURSE_PLANNER";
CREATE VIEW COURSE_PLANNER AS
SELECT 	EVENT.current_semester
		, EVENT.lecture_number
		, LECTURE.lecture_name	
		, EVENT.course
		, LECTURE.semester
		, LECTURE.pwz
		, LECTURE.semester_hours_spo 
		, LECTURE.credit_amount
		, EVENT.semester_hours_actual
		, LECTURE.lecture_comments
		, EVENT.event_comments

FROM LECTURE
FULL OUTER JOIN EVENT
ON LECTURE.lecture_number = EVENT.lecture_number
;

ECHO "CREATE VIEW WORKLOAD_REDUCTION";
CREATE VIEW WORKLOAD_REDUCTION AS
SELECT    R.TERM
		, (SELECT L.NAME FROM LECTURER AS L
			WHERE L.LECTURER_NUMBER = R.LECTURER_NUMBER)
		, R.WORKLOAD_RED_REASON
		, R.WORKLOAD_RED_AMOUNT 
FROM REDUCTION AS R
WHERE R.WORKLOAD_RED_AMOUNT != 0;
	
ECHO "CREATE VIEW MATCHMAKER";
CREATE VIEW MATCHMAKER AS
SELECT
	E.COURSE,
	L.SEMESTER,
	E.CURRENT_SEMESTER,
	L.LECTURE_NUMBER,
	L.LECTURE_NAME,
	L.SEMESTER_HOURS_SPO,
	L.CREDIT_AMOUNT,
	L.PWZ,
	E.SEMESTER_HOURS_SPO_ACTUAL,
	E.SEMESTER_HOURS_ACTUAL,
	E.DEPARTMENT,
	E.DEPARTMENT_IMPORTED_FROM,
	LE.SPLIT_WORKLOAD,
	P.LECTURER_NUMBER,
	P.NAME,
	L.LECTURE_COMMENTS,
	P.LECTURER_COMMENTS,
	E.EVENT_COMMENTS
FROM
	LECTURER_EVENT AS LE
	LEFT OUTER JOIN EVENT AS E
		ON (LE.LECTURE_NUMBER = E.LECTURE_NUMBER AND LE.COURSE = E.COURSE)
	LEFT OUTER JOIN LECTURE AS L
		ON (LE.LECTURE_NUMBER = L.LECTURE_NUMBER)
	LEFT OUTER JOIN LECTURER AS P
		ON (LE.LECTURER_NUMBER = P.LECTURER_NUMBER)
	LEFT OUTER JOIN EVENT_COUPLING AS EC
		ON (LE.COUPLING_ID = EC.COUPLING_ID)
;

