-- @author alriit00, damait06, eumuit00
echo "----------------------------";
echo "EXECUTE: createTables.sql";
echo "----------------------------";
echo "";
echo "CREATE TABLE RAWDATA";
CREATE TABLE RAWDATA
	( sbjNo varchar (15)
	, sbjName varchar (60)
	, sbjlevel varchar (5)
	, dept varchar (5)
	, studyPrg varchar (5)
	, elective varchar (5)
	, numCurr varchar (5)
	, numSchd varchar (5)
	, sbjNotes varchar (50)
	, lecNo varchar (5)
	, lecName varchar (20)
	, lec1stn varchar (20)
	, lecdept varchar (5)
	, lecRoom varchar (10)
	, lecNotes varchar (50)
	, prof varchar (10)
	, linkedWith varchar (20)
	, term varchar (10)
	, cntLec varchar (5)
	, cntCurr varchar (5)
	, cntSchd varchar (5)
	, assNotes varchar (30) )
;

echo "CREATE TABLE RAWDATA_WORKLOAD";
CREATE TABLE RAWDATA_WORKLOAD
	( term varchar (10)
	, name varchar (15)
	, job_title varchar (45)
	, reduction varchar (5) )
;

echo "IMPORT Sample15ws-2.csv";
IMPORT FROM 'Sample15ws-2.csv' of del INSERT INTO "RAWDATA";
echo "IMPORT Sample15ws-2wl.csv";
IMPORT FROM 'Sample15ws-2wl.csv' of del INSERT INTO "RAWDATA_WORKLOAD";

echo "CREATE TABLE DEPARTMENT";
CREATE TABLE DEPARTMENT
	( DEPARTMENT_SHORT varchar (255) NOT NULL
	, DEPARTMENT_NAME varchar (255) )
;

echo "CREATE TABLE EVENT";
CREATE TABLE EVENT
	( LECTURE_NUMBER varchar (255) NOT NULL
	, COURSE varchar (255) NOT NULL
	, CURRENT_SEMESTER varchar (255) NOT NULL
	, SEMESTER_HOURS_ACTUAL integer NOT NULL
	, EVENT_COMMENTS varchar (255)
	, SEMESTER_HOURS_SPO_ACTUAL integer NOT NULL
	, DEPARTMENT varchar (255) NOT NULL
	, DEPARTMENT_IMPORTED_FROM varchar (255) )
;

echo "CREATE TABLE EVENT_COUPLING";
CREATE TABLE EVENT_COUPLING
	( COUPLING_ID integer NOT NULL )
;

echo "CREATE TABLE EXTERNAL_LECTURER";
CREATE TABLE EXTERNAL_LECTURER
	( ZIP_CODE varchar (255) NOT NULL DEFAULT '73732'
	, COUNTRY_CODE varchar (255) NOT NULL DEFAULT 'DE'
	, CITY_NAME varchar (255) NOT NULL DEFAULT 'Esslingen'
	, STREET_NAME varchar (255) DEFAULT 'Flandernstra�e'
	, HOUSE_NR varchar (255) DEFAULT '101'
	, LECTURER_NUMBER varchar (255) NOT NULL )
;

echo "CREATE TABLE LECTURE";
CREATE TABLE LECTURE
	( LECTURE_NUMBER varchar (255) NOT NULL
	, LECTURE_NAME varchar (255) NOT NULL
	, LECTURE_COMMENTS varchar (255)
	, SEMESTER varchar (255) NOT NULL
	, CREDIT_AMOUNT integer NOT NULL
	, PWZ varchar (5) NOT NULL
	, SEMESTER_HOURS_SPO integer NOT NULL )
;

echo "CREATE TABLE LECTURER";
CREATE TABLE LECTURER
	( LECTURER_NUMBER varchar (255) NOT NULL
	, LECTURER_COMMENTS varchar (255)
	, ACTIVE smallint DEFAULT 1 NOT NULL
	, NAME varchar (255) NOT NULL
	, FIRSTNAME varchar (255) NOT NULL )
;

echo "CREATE TABLE LECTURER_EVENT";
CREATE TABLE LECTURER_EVENT
	( LECTURER_NUMBER varchar (255) NOT NULL
	, COURSE varchar (255) NOT NULL
	, LECTURE_NUMBER varchar (255) NOT NULL
	, SPLIT_WORKLOAD float NOT NULL
	, COUPLING_ID integer )
;

echo "CREATE TABLE PROFESSOR";
CREATE TABLE PROFESSOR
	( WORKLOAD_ACTUAL float NOT NULL DEFAULT 18.0
	, DEPARTMENT_SHORT varchar (255) NOT NULL
	, LECTURER_NUMBER varchar (255) NOT NULL )
;

echo "CREATE TABLE REDUCTION";
CREATE TABLE REDUCTION
	( WORKLOAD_RED_REASON varchar (255) NOT NULL
	, LECTURER_NUMBER varchar (255) NOT NULL
	, WORKLOAD_RED_AMOUNT integer NOT NULL
	, TERM varchar (10) NOT NULL )
;	
	
echo "ALTER TABLE DEPARTMENT";
ALTER TABLE DEPARTMENT
	ADD CONSTRAINT PK PRIMARY KEY 
	( DEPARTMENT_SHORT );

echo "ALTER TABLE EVENT";
ALTER TABLE EVENT
	ADD CONSTRAINT PK PRIMARY KEY 
	( COURSE
	, LECTURE_NUMBER );

echo "ALTER TABLE EXTERNAL_LECTURER";	
ALTER TABLE EVENT_COUPLING
	ADD CONSTRAINT PK PRIMARY KEY 
	( COUPLING_ID );

ALTER TABLE EXTERNAL_LECTURER
	ADD CONSTRAINT PK PRIMARY KEY 
	( LECTURER_NUMBER );

echo "ALTER TABLE LECTURE";	
ALTER TABLE LECTURE
	ADD CONSTRAINT PK PRIMARY KEY 
	( LECTURE_NUMBER );

echo "ALTER TABLE LECTURER";	
ALTER TABLE LECTURER
	ADD CONSTRAINT PK PRIMARY KEY 
	( LECTURER_NUMBER );

echo "ALTER TABLE LECTURER_EVENT";	
ALTER TABLE LECTURER_EVENT
	ADD CONSTRAINT PK PRIMARY KEY 
	( COURSE
	, LECTURE_NUMBER
	, LECTURER_NUMBER );

	
echo "ALTER TABLE PROFESSOR";
ALTER TABLE PROFESSOR
	ADD CONSTRAINT PK PRIMARY KEY 
	( LECTURER_NUMBER );

echo "ALTER TABLE REDUCTION";	
ALTER TABLE REDUCTION
	ADD CONSTRAINT PK PRIMARY KEY 
	( WORKLOAD_RED_REASON
	, LECTURER_NUMBER );

echo "ALTER TABLE EVENT";
ALTER TABLE EVENT
	ADD CONSTRAINT EVENT_LECTURE FOREIGN KEY
	( LECTURE_NUMBER )
	REFERENCES LECTURE
	( LECTURE_NUMBER )
	ON DELETE CASCADE; 

echo "ALTER TABLE EVENT";
ALTER TABLE EVENT
	ADD CONSTRAINT EVENT_DEPARTMENT FOREIGN KEY
	( DEPARTMENT )
	REFERENCES DEPARTMENT
	( DEPARTMENT_SHORT ); 

echo "ALTER TABLE EVENT";	
ALTER TABLE EVENT
	ADD CONSTRAINT EVENT_DEPARTMENT_38 FOREIGN KEY
	( DEPARTMENT_IMPORTED_FROM )
	REFERENCES DEPARTMENT
	( DEPARTMENT_SHORT ); 

echo "ALTER TABLE EXTERNAL_LECTURER_LECTURER";	
ALTER TABLE EXTERNAL_LECTURER
	ADD CONSTRAINT EXTERNAL_LECTURER_LECTURER FOREIGN KEY
	( LECTURER_NUMBER )
	REFERENCES LECTURER
	( LECTURER_NUMBER )
	ON DELETE CASCADE; 

echo "ALTER TABLE LECTURER_EVENT";	
ALTER TABLE LECTURER_EVENT
	ADD CONSTRAINT LECTURER_EVENT_LECTURER FOREIGN KEY
	( LECTURER_NUMBER )
	REFERENCES LECTURER
	( LECTURER_NUMBER )
	ON DELETE CASCADE; 

echo "ALTER TABLE LECTURER_EVENT";	
ALTER TABLE LECTURER_EVENT
	ADD CONSTRAINT LECTURER_EVENT_EVENT FOREIGN KEY
	( COURSE
	, LECTURE_NUMBER )
	REFERENCES EVENT
	( COURSE
	, LECTURE_NUMBER )
	ON DELETE CASCADE; 

echo "ALTER TABLE LECTURER_EVENT";	
ALTER TABLE LECTURER_EVENT
	ADD CONSTRAINT LECTURER_EVENT_EVENT_COUPLING FOREIGN KEY
	( COUPLING_ID )
	REFERENCES EVENT_COUPLING
	( COUPLING_ID ); 

echo "ALTER TABLE PROFESSOR_LECTURER";	
ALTER TABLE PROFESSOR
	ADD CONSTRAINT PROFESSOR_LECTURER FOREIGN KEY
	( LECTURER_NUMBER )
	REFERENCES LECTURER
	( LECTURER_NUMBER )
	ON DELETE CASCADE; 

echo "ALTER TABLE PROFESSOR";	
ALTER TABLE PROFESSOR
	ADD CONSTRAINT PROFESSOR_DEPARTMENT FOREIGN KEY
	( DEPARTMENT_SHORT )
	REFERENCES DEPARTMENT
	( DEPARTMENT_SHORT ); 

