CREATE TABLE DEPARTMENT
	( DEPARTMENT_SHORT char NOT NULL
	, DEPARTMENT_NAME char )
;

CREATE TABLE EVENT
	( LECTURE_NR char NOT NULL
	, COURSE char NOT NULL
	, CURRENT_SEMESTER char NOT NULL
	, SPO char NOT NULL
	, DEPARTMENT char NOT NULL
	, IMPORTED_FROM_DEPARTMENT char
	, SEMESTER_HOURS_ACTUAL integer NOT NULL
	, COMMENT char
	, DEPARTMENT_124 char NOT NULL
	, DEPARTMENT_IMPORTED_FROM char )
;

CREATE TABLE EXTERNAL_LECTURER
	( ZIP_CODE char NOT NULL
	, COUNTRY_CODE char NOT NULL
	, CITY_NAME char NOT NULL
	, STREET_NAME char
	, HOUSE_NR char
	, LECTURER_NUMBER char NOT NULL )
;

CREATE TABLE LECTURE
	( LECTURE_NR char NOT NULL
	, LECTURE_NAME char NOT NULL
	, SEMESTER char NOT NULL
	, EXAM_TYPE char NOT NULL
	, EXAM_DURATION integer NOT NULL
	, CREDIT_AMOUNT integer NOT NULL
	, PWZ char NOT NULL
	, SEMESTER_HOURS_SPO integer NOT NULL )
;

CREATE TABLE LECTURER
	( LECTURER_NUMBER char NOT NULL
	, NAME char NOT NULL
	, FIRSTNAME char NOT NULL )
;

CREATE TABLE LECTURER_EVENT
	( LECTURER_NUMBER char NOT NULL
	, COURSE char NOT NULL
	, LECTURE_NR char NOT NULL
	, WORKLOAD_ACTUAL integer NOT NULL
	, COUPLING_ID integer )
;

CREATE TABLE PROFESSOR
	( WORKLOAD_RED_REASON char NOT NULL
	, WORKLOAD_REGULAR integer NOT NULL
	, WORKLOAD_RED_AMOUNT integer NOT NULL
	, DEPARTMENT_SHORT char NOT NULL
	, LECTURER_NUMBER char NOT NULL )
;