CREATE TABLE DEPARTMENT
	( DEPARTMENT_SHORT varchar (255) NOT NULL
	, DEPARTMENT_NAME varchar (255) )
;
GRANT ALL ON DEPARTMENT TO PUBLIC;

CREATE TABLE EVENT
	( LECTURE_NR varchar (255) NOT NULL
	, COURSE varchar (255) NOT NULL
	, CURRENT_SEMESTER varchar (255) NOT NULL
	, SPO varchar (255) NOT NULL
	, DEPARTMENT varchar (255) NOT NULL
	, IMPORTED_FROM_DEPARTMENT varchar (255)
	, SEMESTER_HOURS_ACTUAL integer NOT NULL
	, COMMENT varchar (255)
	, DEPARTMENT_124 varchar (255) NOT NULL
	, DEPARTMENT_IMPORTED_FROM varchar (255) )
;
GRANT ALL ON EVENT TO PUBLIC;

CREATE TABLE EXTERNAL_LECTURER
	( ZIP_CODE varchar (255) NOT NULL
	, COUNTRY_CODE varchar (255) NOT NULL
	, CITY_NAME varchar (255) NOT NULL
	, STREET_NAME varchar (255)
	, HOUSE_NR varchar (255)
	, LECTURER_NUMBER varchar (255) NOT NULL )
;
GRANT ALL ON EXTERNAL_LECTURER TO PUBLIC;

CREATE TABLE LECTURE
	( LECTURE_NR varchar (255) NOT NULL
	, LECTURE_NAME varchar (255) NOT NULL
	, SEMESTER varchar (255) NOT NULL
	, EXAM_TYPE varchar (255) NOT NULL
	, EXAM_DURATION integer NOT NULL
	, CREDIT_AMOUNT integer NOT NULL
	, PWZ varchar (255) NOT NULL
	, SEMESTER_HOURS_SPO integer NOT NULL )
;
GRANT ALL ON LECTURE TO PUBLIC;

CREATE TABLE LECTURER
	( LECTURER_NUMBER varchar (255) NOT NULL
	, NAME varchar (255) NOT NULL
	, FIRSTNAME varchar (255) NOT NULL )
;
GRANT ALL ON LECTURER TO PUBLIC;

CREATE TABLE LECTURER_EVENT
	( LECTURER_NUMBER varchar (255) NOT NULL
	, COURSE varchar (255) NOT NULL
	, LECTURE_NR varchar (255) NOT NULL
	, WORKLOAD_ACTUAL integer NOT NULL
	, COUPLING_ID integer )
;
GRANT ALL ON LECTURER_EVENT TO PUBLIC;

CREATE TABLE PROFESSOR
	( WORKLOAD_RED_REASON varchar (255) NOT NULL
	, WORKLOAD_REGULAR integer NOT NULL
	, WORKLOAD_RED_AMOUNT integer NOT NULL
	, DEPARTMENT_SHORT varchar (255) NOT NULL
	, LECTURER_NUMBER varchar (255) NOT NULL )
;
GRANT ALL ON PROFESSOR TO PUBLIC;