-- @author alriit00, damait06
DROP TABLE RAWDATA;
DROP TABLE RAWDATA_WORKLOAD;
DROP TABLE DEPARTMENT;
DROP TABLE EVENT;
DROP TABLE EXTERNAL_LECTURER;
DROP TABLE LECTURE;
DROP TABLE LECTURER;
DROP TABLE LECTURER_EVENT;
DROP TABLE PROFESSOR;
DROP TABLE EVENT_COUPLING;
