-- @author alriit00, damait06
GRANT ALL ON RAWDATA TO PUBLIC;
GRANT ALL ON RAWDATA_WORKLOAD TO PUBLIC;
GRANT ALL ON DEPARTMENT TO PUBLIC;
GRANT ALL ON EVENT TO PUBLIC;
GRANT ALL ON EXTERNAL_LECTURER TO PUBLIC;
GRANT ALL ON LECTURE TO PUBLIC;
GRANT ALL ON LECTURER TO PUBLIC;
GRANT ALL ON LECTURER_EVENT TO PUBLIC;
GRANT ALL ON PROFESSOR TO PUBLIC;
GRANT ALL ON EVENT_COUPLING TO PUBLIC;

GRANT ALL ON Course_Planner TO PUBLIC;
GRANT ALL ON WORKLOAD_REDUCTION TO PUBLIC;
GRANT ALL ON MATCHMAKER TO PUBLIC;
GRANT ALL ON SERVICE_PLANNER TO PUBLIC;


