-- @author alriit00, damait06, eumuit00
echo "----------------------------";
echo "EXECUTE: grantRights.sql";
echo "----------------------------";
echo "";
echo "GRANT ALL ON RAWDATA TO PUBLIC";
GRANT ALL ON RAWDATA TO PUBLIC;
echo "GRANT ALL ON RAWDATA_WORKLOAD TO PUBLIC";
GRANT ALL ON RAWDATA_WORKLOAD TO PUBLIC;
echo "GRANT ALL ON DEPARTMENT TO PUBLIC";
GRANT ALL ON DEPARTMENT TO PUBLIC;
echo "GRANT ALL ON EVENT TO PUBLIC";
GRANT ALL ON EVENT TO PUBLIC;
echo "GRANT ALL ON EXTERNAL_LECTURER TO PUBLIC";
GRANT ALL ON EXTERNAL_LECTURER TO PUBLIC;
echo "GRANT ALL ON LECTURE TO PUBLIC";
GRANT ALL ON LECTURE TO PUBLIC;
echo "GRANT ALL ON LECTURER TO PUBLIC";
GRANT ALL ON LECTURER TO PUBLIC;
echo "GRANT ALL ON LECTURER_EVENT TO PUBLIC";
GRANT ALL ON LECTURER_EVENT TO PUBLIC;
echo "GRANT ALL ON PROFESSOR TO PUBLIC";
GRANT ALL ON PROFESSOR TO PUBLIC;
echo "GRANT ALL ON EVENT_COUPLING TO PUBLIC";
GRANT ALL ON EVENT_COUPLING TO PUBLIC;
echo "GRANT ALL ON COURSE_PLANNER TO PUBLIC";
GRANT ALL ON COURSE_PLANNER TO PUBLIC;
echo "GRANT ALL ON WORKLOAD_REDUCTION TO PUBLIC";
GRANT ALL ON WORKLOAD_REDUCTION TO PUBLIC;
echo "GRANT ALL ON MATCHMAKER TO PUBLIC";
GRANT ALL ON MATCHMAKER TO PUBLIC;

echo "GRANT ALL ON COURSE_PLANNER TO EUMUIT00";
GRANT ALL ON COURSE_PLANNER TO EUMUIT00;
echo "GRANT ALL ON WORKLOAD_REDUCTION TO EUMUIT00";
GRANT ALL ON WORKLOAD_REDUCTION TO EUMUIT00;
echo "GRANT ALL ON MATCHMAKER TO EUMUIT00";
GRANT ALL ON MATCHMAKER TO EUMUIT00;





