CREATE TABLE DEPARTMENT
	( DEPARTMENT_SHORT varchar (255) NOT NULL
	, DEPARTMENT_NAME varchar (255) )
;

CREATE TABLE EVENT
	( LECTURE_NR varchar (255) NOT NULL
	, COURSE varchar (255) NOT NULL
	, CURRENT_SEMESTER varchar (255) NOT NULL
	, SPO varchar (255) NOT NULL
	, SEMESTER_HOURS_ACTUAL integer NOT NULL
	, COMMENT varchar (255)
	, DEPARTMENT varchar (255) NOT NULL
	, DEPARTMENT_IMPORTED_FROM varchar (255) )
;

CREATE TABLE EXTERNAL_LECTURER
	( ZIP_CODE varchar (255) NOT NULL
	, COUNTRY_CODE varchar (255) NOT NULL
	, CITY_NAME varchar (255) NOT NULL
	, STREET_NAME varchar (255)
	, HOUSE_NR varchar (255)
	, LECTURER_NUMBER varchar (255) NOT NULL )
;

CREATE TABLE LECTURE
	( LECTURE_NR varchar (255) NOT NULL
	, LECTURE_NAME varchar (255) NOT NULL
	, SEMESTER varchar (255) NOT NULL
	, EXAM_TYPE varchar (255) NOT NULL
	, EXAM_DURATION integer NOT NULL
	, CREDIT_AMOUNT integer NOT NULL
	, PWZ varchar (255) NOT NULL
	, SEMESTER_HOURS_SPO integer NOT NULL )
;

CREATE TABLE LECTURER
	( LECTURER_NUMBER varchar (255) NOT NULL
	, NAME varchar (255) NOT NULL
	, FIRSTNAME varchar (255) NOT NULL )
;

CREATE TABLE LECTURER_EVENT
	( LECTURER_NUMBER varchar (255) NOT NULL
	, COURSE varchar (255) NOT NULL
	, LECTURE_NR varchar (255) NOT NULL
	, WORKLOAD_ACTUAL integer NOT NULL
	, COUPLING_ID integer )
;

CREATE TABLE PROFESSOR
	( WORKLOAD_RED_REASON varchar (255) NOT NULL
	, WORKLOAD_REGULAR integer NOT NULL
	, WORKLOAD_RED_AMOUNT integer NOT NULL
	, DEPARTMENT_SHORT varchar (255) NOT NULL
	, LECTURER_NUMBER varchar (255) NOT NULL )
;

ALTER TABLE DEPARTMENT
	ADD CONSTRAINT PK PRIMARY KEY 
	( DEPARTMENT_SHORT );

ALTER TABLE EVENT
	ADD CONSTRAINT PK PRIMARY KEY 
	( COURSE
	, LECTURE_NR );

ALTER TABLE EXTERNAL_LECTURER
	ADD CONSTRAINT PK PRIMARY KEY 
	( LECTURER_NUMBER );

ALTER TABLE LECTURE
	ADD CONSTRAINT PK PRIMARY KEY 
	( LECTURE_NR );

ALTER TABLE LECTURER
	ADD CONSTRAINT PK PRIMARY KEY 
	( LECTURER_NUMBER );

ALTER TABLE LECTURER_EVENT
	ADD CONSTRAINT PK PRIMARY KEY 
	( COURSE
	, LECTURE_NR
	, LECTURER_NUMBER );

ALTER TABLE PROFESSOR
	ADD CONSTRAINT PK PRIMARY KEY 
	( WORKLOAD_RED_REASON
	, LECTURER_NUMBER );

ALTER TABLE EVENT
	ADD CONSTRAINT EVENT_LECTURE FOREIGN KEY
	( LECTURE_NR )
	REFERENCES LECTURE
	( LECTURE_NR )
	ON DELETE CASCADE; 

ALTER TABLE EVENT
	ADD CONSTRAINT EVENT_DEPARTMENT FOREIGN KEY
	( DEPARTMENT )
	REFERENCES DEPARTMENT
	( DEPARTMENT_SHORT ); 

ALTER TABLE EVENT
	ADD CONSTRAINT EVENT_DEPARTMENT_37 FOREIGN KEY
	( DEPARTMENT_IMPORTED_FROM )
	REFERENCES DEPARTMENT
	( DEPARTMENT_SHORT ); 

ALTER TABLE EXTERNAL_LECTURER
	ADD CONSTRAINT EXTERNAL_LECTURER_LECTURER FOREIGN KEY
	( LECTURER_NUMBER )
	REFERENCES LECTURER
	( LECTURER_NUMBER )
	ON DELETE CASCADE; 

ALTER TABLE LECTURE
	ADD CONSTRAINT LECTURE_DEPARTMENT FOREIGN KEY
	(  )
	REFERENCES 
	(  ); 

ALTER TABLE LECTURE
	ADD CONSTRAINT LECTURE_DEPARTMENT_39 FOREIGN KEY
	(  )
	REFERENCES 
	(  ); 

ALTER TABLE LECTURER_EVENT
	ADD CONSTRAINT LECTURER_EVENT_LECTURER FOREIGN KEY
	( LECTURER_NUMBER )
	REFERENCES LECTURER
	( LECTURER_NUMBER )
	ON DELETE CASCADE; 

ALTER TABLE LECTURER_EVENT
	ADD CONSTRAINT LECTURER_EVENT_EVENT FOREIGN KEY
	( COURSE
	, LECTURE_NR )
	REFERENCES EVENT
	( COURSE
	, LECTURE_NR )
	ON DELETE CASCADE; 

ALTER TABLE PROFESSOR
	ADD CONSTRAINT PROFESSOR_LECTURER FOREIGN KEY
	( LECTURER_NUMBER )
	REFERENCES LECTURER
	( LECTURER_NUMBER )
	ON DELETE CASCADE; 

ALTER TABLE PROFESSOR
	ADD CONSTRAINT PROFESSOR_DEPARTMENT FOREIGN KEY
	( DEPARTMENT_SHORT )
	REFERENCES DEPARTMENT
	( DEPARTMENT_SHORT ); 

