CREATE TABLE EVENT
	( LECTURE_NUMBER varchar (255) NOT NULL
	, COURSE varchar (255) NOT NULL
	, CURRENT_SEMESTER varchar (255) NOT NULL
	, SPO varchar (255) NOT NULL
	, SEMESTER_HOURS_ACTUAL integer NOT NULL
	, EVENT_COMMENTS varchar (255)
	, SEMESTER_HOURS_SPO_ACTUAL integer NOT NULL
	, DEPARTMENT varchar (255) NOT NULL
	, DEPARTMENT_IMPORTED_FROM varchar (255) )
;

CREATE TABLE EVENT_COUPLING
	( COUPLING_ID integer NOT NULL )
;

CREATE TABLE LECTURE
	( LECTURE_NUMBER varchar (255) NOT NULL
	, LECTURE_NAME varchar (255) NOT NULL
	, LECTURE_COMMENTS varchar (255)
	, SEMESTER varchar (255) NOT NULL
	, EXAM_TYPE varchar (255) NOT NULL
	, EXAM_DURATION integer NOT NULL
	, CREDIT_AMOUNT integer NOT NULL
	, PWZ varchar (255) NOT NULL
	, SEMESTER_HOURS_SPO integer NOT NULL )
;

CREATE TABLE LECTURER
	( LECTURER_NUMBER varchar (255) NOT NULL
	, LECTURER_COMMENTS varchar (255)
	, NAME varchar (255) NOT NULL
	, FIRSTNAME varchar (255) NOT NULL )
;

CREATE TABLE LECTURER_EVENT
	( LECTURER_NUMBER varchar (255) NOT NULL
	, COURSE varchar (255) NOT NULL
	, LECTURE_NUMBER varchar (255) NOT NULL
	, LECTURER_WORKLOAD_ACTUAL integer NOT NULL
	, SCHEDULE_WORKLOAD_ACTUAL integer NOT NULL
	, COUPLING_ID integer )
;

ALTER TABLE EVENT
	ADD CONSTRAINT PK PRIMARY KEY 
	( COURSE
	, LECTURE_NUMBER );

ALTER TABLE EVENT_COUPLING
	ADD CONSTRAINT PK PRIMARY KEY 
	( COUPLING_ID );

ALTER TABLE LECTURE
	ADD CONSTRAINT PK PRIMARY KEY 
	( LECTURE_NUMBER );

ALTER TABLE LECTURER
	ADD CONSTRAINT PK PRIMARY KEY 
	( LECTURER_NUMBER );

ALTER TABLE LECTURER_EVENT
	ADD CONSTRAINT PK PRIMARY KEY 
	( COURSE
	, LECTURE_NUMBER
	, LECTURER_NUMBER );

ALTER TABLE EVENT
	ADD CONSTRAINT EVENT_LECTURE FOREIGN KEY
	( LECTURE_NUMBER )
	REFERENCES LECTURE
	( LECTURE_NUMBER )
	ON DELETE CASCADE; 

ALTER TABLE EVENT
	ADD CONSTRAINT EVENT_DEPARTMENT FOREIGN KEY
	( DEPARTMENT )
	REFERENCES DEPARTMENT
	( DEPARTMENT_SHORT ); 

ALTER TABLE EVENT
	ADD CONSTRAINT EVENT_DEPARTMENT_37 FOREIGN KEY
	( DEPARTMENT_IMPORTED_FROM )
	REFERENCES DEPARTMENT
	( DEPARTMENT_SHORT ); 

ALTER TABLE LECTURER_EVENT
	ADD CONSTRAINT LECTURER_EVENT_LECTURER FOREIGN KEY
	( LECTURER_NUMBER )
	REFERENCES LECTURER
	( LECTURER_NUMBER )
	ON DELETE CASCADE; 

ALTER TABLE LECTURER_EVENT
	ADD CONSTRAINT LECTURER_EVENT_EVENT FOREIGN KEY
	( COURSE
	, LECTURE_NUMBER )
	REFERENCES EVENT
	( COURSE
	, LECTURE_NUMBER )
	ON DELETE CASCADE; 

ALTER TABLE LECTURER_EVENT
	ADD CONSTRAINT LECTURER_EVENT_EVENT_COUPLING FOREIGN KEY
	( COUPLING_ID )
	REFERENCES EVENT_COUPLING
	( COUPLING_ID ); 

